// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFIOON7YJHUaCzvz3b7tHqYW9CYqZKE_M',
    appId: '1:84929515597:web:803557596e21fabcabcc04',
    messagingSenderId: '84929515597',
    projectId: 'todoapp-ff1a7',
    authDomain: 'todoapp-ff1a7.firebaseapp.com',
    storageBucket: 'todoapp-ff1a7.firebasestorage.app',
    measurementId: 'G-Q5X6EF6NK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Iq-IlTovCk7xJSxqadaftrCRefVuaKM',
    appId: '1:84929515597:android:7e6e05c95738426fabcc04',
    messagingSenderId: '84929515597',
    projectId: 'todoapp-ff1a7',
    storageBucket: 'todoapp-ff1a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXJJRn2bvvAT4naXPmlm3Ec2IEt9B6Xq0',
    appId: '1:84929515597:ios:256c8c931760b07dabcc04',
    messagingSenderId: '84929515597',
    projectId: 'todoapp-ff1a7',
    storageBucket: 'todoapp-ff1a7.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
